CREATE TABLE clientes (
  id BIGINT PRIMARY KEY,
  cpf VARCHAR(11) NOT NULL UNIQUE,
  nascimento DATE NOT NULL,
  genero VARCHAR(20) NOT NULL,
  ddd VARCHAR(3) NOT NULL,
  telefone VARCHAR(9) NOT NULL,
  tipo_Telefone VARCHAR(255) NOT NULL
);